### PR TITLE
Add basic test and add process log and upload function

### LINKED ISSUE #14: enable progress log
Hi

I think it would be nice to have an option to log the progress. Especially on large collections it would be helpful to know on which position of the generation the script is at.

Cheers

### PR DESCRIPTION
**Pull request by dohomi**
Hi @juliancwirko 

I took the initiative to create a basic test environment and added a simple logger to see the process of the `startCreating` function. 

This would close #14

### CODE REVIEW

**Comment by dohomi** [comment]
@juliancwirko I created a basic nft.storage upload function. 

This would close #12

**Comment by juliancwirko** [comment]
Hey, nice, thanks. I'll review it soon. 

Btw, as for tests, I would keep all the files test related in the test directory, and I also think they should be done on mocks somehow, not actual calls of the functions

**Comment by dohomi** [comment]
@juliancwirko feel free to cherry pick any functionality. I also think its better to move the example files into the tests folder as well - i just didn't want to move to many things around without double check. 

About the mocks, I think the only function which is questionable is the actual upload function - the other test is quite simple and runs the example nft and checks if the generation works - that can't be mocked.

**Comment by juliancwirko** [comment]
Cool, I'll check it in the evening CEST. Maybe we could leave the tests on actual operations. It is always better than nothing :) I would keep the 'example' separated to avoid confusing users who are not so techy. Maybe tests could use the .nftartmakerrc from example dir?

**Comment by dohomi** [comment]
currently the tests use the .nftarmakerrc from the root (I wasn't sure how to update the script to run from example folder)

**Comment by juliancwirko** [comment]
ahhh, you're right. I'll check how we could improve that

**Comment by juliancwirko** [comment]
Hey, @dohomi, please check the new pull request (https://github.com/juliancwirko/nft-art-maker/pull/18) with your changes and a couple of my changes. Let me know if it is ok, then we could merge it, and then I will bump the version's changelog and publish it. It works very well. Thanks a lot.

**Comment by dohomi** [comment]
it looks good ready to merge

**Pull request merged**
